services:
  app:
    platform: linux/amd64
    image: php-oracle
    container_name: auto-rent-app
    build:
      context: app-dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.compose
#    environment:
#      ENV: 'dev'
#      BUILD: true
#      MIGRATE: true
#      KILL: false
#      USER_UID: 1000
#      USER_GID: 1000
    volumes:
      - '.:/app'
      -