services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: db-auto-rent
    restart: unless-stopped
    ports:
     - "1521:1521"
    environment:
      ORACLE_PWD: ApassW0rd
      ORACLE_CHARACTERSET: UTF8
    volumes:
      - auto-rent-db:/opt/oracle/oradata

# TODO: add env file to read the .env
  app:
    image: php-oracle
    container_name: auto-rent-app
    build:
      context: app-dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.compose
#    environment:
#      ENV: 'dev'
#      BUILD: true
#      MIGRATE: true
#      KILL: false
#      USER_UID: 1000
#      USER_GID: 1000
    volumes:
      - '.:/app'
    depends_on:
      - db
volumes:
  auto-rent-db:
