FROM oraclelinux:9
ENV PATH=/usr/lib/oracle/23/client64/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/lib/oracle/23/client64/lib:$LD_LIBRARY_PATH

RUN dnf install https://rpms.remirepo.net/enterprise/remi-release-9.rpm && \
    dnf module reset php:remi-8.3 && \
    dnf update && \
    dnf module install php:remi-8.4 && \
    dnf install php-raphf && \
    dnf install php-http && \
    dnf install php-pdo && \
    dnf install git && \
    dnf install zip && \
    dnf -y install oracle-instantclient-release-23ai-el9 && \
    dnf -y install oracle-instantclient-basic oracle-instantclient-devel && \
    dnf install php-oci8 && \
    rm -rf /var/cache/dnf && \
    mkdir /app

COPY entry-script.sh /root/entry-point.sh
EXPOSE 8080
WORKDIR /app
ENTRYPOINT ["/bin/bash", "/root/entry-point.sh"]

